# Generated by Django 5.2.7 on 2025-10-25 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0003_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_color', models.CharField(default='#2c3e50', max_length=7)),
                ('secondary_color', models.CharField(default='#3498db', max_length=7)),
                ('accent_color', models.CharField(default='#e74c3c', max_length=7)),
                ('font_family', models.CharField(default='Arial, sans-serif', max_length=50)),
                ('layout_style', models.CharField(default='modern', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='template',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv_app.cvtemplate'),
        ),
    ]
